# This test file was generated by ChatGPT, speeds up the unit testing part.
from affine import AffineForm
from intervals import Interval

# Helper to pretty print


def show(label, a):
    print(f"{label}:")
    print("  affine :", a)
    print("  interval:", a.to_interval())
    print()


# ---- Test 1: creation from interval ----
x = AffineForm.from_interval(Interval(2, 6))
show("x from [2,6]", x)

# ---- Test 2: two independent intervals ----
x = AffineForm.from_interval(Interval(2, 6))
y = AffineForm.from_interval(Interval(10, 14))
show("x", x)
show("y", y)

# ---- Test 3: addition (no new ε) ----
z = x + y
show("z = x + y", z)

# ---- Test 4: subtraction and dependency ----
x = AffineForm.from_interval(Interval(0, 1))
f = x - x
show("f(x) = x - x", f)

# ---- Test 5: multiplication introduces new ε ----
x = AffineForm.from_interval(Interval(2, 6))   # 4 + 2ε1
y = AffineForm.from_interval(Interval(3, 5))   # 4 + 1ε2
z = x * y
show("z = x * y", z)

# ---- Test 6: square function (nonlinear) ----
x = AffineForm.from_interval(Interval(-1, 1))
f = x * x
show("f(x) = x^2", f)

# ---- Test 7: division ----
x = AffineForm.from_interval(Interval(2, 4))
y = AffineForm.from_interval(Interval(1, 2))
f = x / y
show("f(x) = x / y", f)

# ---- Test 8: negation ----
x = AffineForm.from_interval(Interval(1, 3))
f = -x
show("f(x) = -x", f)

# ---- Test 9: shared noise symbols (zonotope) ----
eps = AffineForm.new_noise()
x1 = AffineForm(10, {eps: 1})
x2 = AffineForm(20, {eps: 2})
show("x1", x1)
show("x2", x2)
z = x1 + x2
show("z = x1 + x2 (shared ε)", z)

# ---- Test 10: chaining multiple operations ----
x = AffineForm.from_interval(Interval(1, 2))
y = AffineForm.from_interval(Interval(2, 3))
f = ((x + y) * x - y) / x
show("f(x,y) = ((x + y) * x - y) / x", f)
